version: "3.5"
services:
  db:
    image: mysql:8
    container_name: gorm.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: gorm
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: gorm
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
